Probleme de Monty Hall
===================



In [1]:
# Pour afficher les graphiques dans la continuité du code, 
# et non pas dans une fenêtre à part:
%matplotlib inline

import numpy as np

# Pour utiliser la fonction randint, qui génère des nombres
# entiers de façon aléatoire:
from random import randint, seed

# Un Enum est une structure de données qui consiste en un 
# ensemble d'éléments nommés. Une variable de ce type peut
# avoir comme valeur un de ces éléments.
from enum import Enum

# Pour pouvoir afficher des graphiques:
import matplotlib.pyplot as plt

In [3]:
# Ici nous définissons une sous-classe de Enum, qui contiendra 
# les stratégies possibles.
class Strategie(Enum):
    CHANGER = 1
    GARDER = 2


In [5]:
a = np.array([0, 1, 2])
print(a)

[0 1 2]


In [6]:
b = randint(0, 2)
print(b)


2


In [7]:
a

array([0, 1, 2])

In [4]:
# Utilise l'horloge système pour initialiser le générateur de 
# nombres pseudo-aléatoires.
seed()

def play_game(strategie):
    '''Simule une partie du jeu Monty Hall.
    
    Cette fonction simule le choix de la porte par le participant, 
    l'élimination d'une mauvaise porte par le présentateur, et le 
    choix final. Elle ne retourne que le résultat de la partie, parce 
    que nous n'aurons besoin que du résultat pour effectuer nos calculs.
    
    Args:
        strategie (Strategie): La stratégie du joueur
        
    Returns:
        bool: Le joueur a-t-il gagné?
    '''

    portes = np.array([0, 1, 2])
    
    bonne_porte = randint(0,2)
    
    # Choix du joueur
    premier_choix = randint(0,2)
    
    # Il nous reste deux portes
    portes.remove(premier_choix)
    
    # Le présentateur élimine une porte
    if premier_choix == bonne_porte:
        portes.remove(portes[randint(0,1)])
    else:
        portes = [bonne_porte]
    
    deuxieme_choix = 0
    # Le deuxieme choix depend de la strategie
    if strategie == Strategie.CHANGER:
        deuxieme_choix = portes[0]
    elif strategie == Strategie.GARDER:
        deuxieme_choix = premier_choix
    else:
        raise ValueError("Stratégie non reconnue!")
    
    return deuxieme_choix == bonne_porte


In [5]:
seed()
print("Premier nombre aléatoire: {}".format(randint(0,100)))
print("Deuxième nombre aléatoire: {}".format(randint(0,100)))

seed(1)
print("Premier nombre aléatoire: {}".format(randint(0,100)))
print("Deuxième nombre aléatoire: {}".format(randint(0,100)))

seed(1)
# Les deux prochains appels vont retourner le même résultat que les deux précédents
print("Premier nombre aléatoire: {}".format(randint(0,100)))
print("Deuxième nombre aléatoire: {}".format(randint(0,100)))

Premier nombre aléatoire: 71
Deuxième nombre aléatoire: 97
Premier nombre aléatoire: 17
Deuxième nombre aléatoire: 72
Premier nombre aléatoire: 17
Deuxième nombre aléatoire: 72


In [6]:
def play(strategie, nb_tours):
    '''Simule une suite de tours du jeu.
    
    Cette fonction renvoie les résultats de plusieurs parties
    du jeu Monty Hall sous forme d'une liste de gains par le 
    joueur.
    
    Args:
        strategie (Strategie): La strategie du joueur
        nb_tours (int): Nombre de tours
        
    Returns:
        list: Liste des gains du joueurs à chaque partie
    '''
    
    # Ceci est une liste en compréhension. Pour en savoir plus, consulter 
    # le cours "Apprenez à programmer en Python" sur OpenClassrooms
    return [1 if play_game(strategie) else 0 for i in range(nb_tours)]


In [7]:
print("En changeant de porte, le joueur a gagné {} sur 10000 parties."
      .format(sum(play(Strategie.CHANGER, 10000))))
      
print("En gardant son choix initial, le joueur a gagné {} sur 10000 parties."
      .format(sum(play(Strategie.GARDER, 10000))))

En changeant de porte, le joueur a gagné 6666 sur 10000 parties.
En gardant son choix initial, le joueur a gagné 3319 sur 10000 parties.


In [12]:
seed()
for i in range(0, 10):
    print("{} - nombre aléatoire: {}".format(i, randint(1, 2)))

print(Strategie.CHANGER)

0 - nombre aléatoire: 1
1 - nombre aléatoire: 2
2 - nombre aléatoire: 2
3 - nombre aléatoire: 1
4 - nombre aléatoire: 2
5 - nombre aléatoire: 1
6 - nombre aléatoire: 1
7 - nombre aléatoire: 2
8 - nombre aléatoire: 1
9 - nombre aléatoire: 1
Strategie.CHANGER


In [15]:
def play_random(nb_tours):
    '''Simule une suite de tours du jeu.
    
    Cette fonction renvoie les résultats de plusieurs parties
    du jeu Monty Hall sous forme d'une liste de gains par le 
    joueur.
    
    Args:
        strategie (Strategie): La strategie du joueur
        nb_tours (int): Nombre de tours
        
    Returns:
        list: Liste des gains du joueurs à chaque partie
    '''
    
    tour = []
    seed()
    
    for i in range(nb_tours):
        alea = randint(1, 2)
        
        if alea == 1:
            strategie = Strategie.GARDER
        else:
            strategie = Strategie.CHANGER
            
        if play_game(strategie):
            tour.append(1)
        else:
            tour.append(0)
            
    return tour

In [19]:
print("En changeant de porte, le joueur a gagné {} sur 10000 parties."
      .format(sum(play_random(10000))))

En changeant de porte, le joueur a gagné 49840 sur 10000 parties.


Three doors in the Monty Hall Problem

In [10]:
portes = np.array([1, 2, 3])

n_tour = 5
porte_bonne = np.random.choice(doors, n_tour)
porte_choisie = np.random.choice(doors, n_tour)

print(porte_bonne)
print(porte_choisie)

print(np)

[2 2 1 3 2]
[2 3 3 3 1]


In [11]:
import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm #allows us easy access to colormaps
import matplotlib.pyplot as plt #sets up plotting under plt
import pandas as pd #lets us handle data as dataframes
#sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns #sets up styles and gives us more plotting options

#Set Parameters
nsim = 1000 # simulation times
doors = 10 # number of dooors, must be >2 integers


In [12]:
def simulate_prizedoor(nsim):
    return np.random.randint(0, doors, (nsim))

def simulate_guess(nsim):
    return np.random.randint(0, doors, (nsim))

def goat_door(prizedoors, guesses):
   out = pd.DataFrame();
   while out.shape[1] != nsim:
    for t in range(0, nsim):
        if prizedoors[t] == guesses[t]:
            same_thing = prizedoors[t]
            out[t] = np.random.choice([x for x in range(0,doors) if x != same_thing], doors-2, replace = False)
        else:
            out[t] = [x for x in range(0,doors) if x != prizedoors[t] and x != guesses[t]]
    return out    

def switch_guess(guesses, goatdoors):
    result = pd.DataFrame()
    for t in range(0, nsim):
        result[t] = list(set(range(0,doors)) - set([guesses[t]]) - set(goatdoors[t]))
    return result

In [14]:
def win_percentage(guesses, prizedoors):
    return 100 * (guesses == prizedoors).mean()

#keep guesses
print("When there are", doors, "doors, win percentage when keeping original door is")
print(win_percentage(simulate_guess(nsim), simulate_prizedoor(nsim)))

#switch
prize = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(prize, guess)

guess = switch_guess(guess, goats)
print ("On the other hand, if switching the win percentage is")
print(win_percentage(prize, guess).mean())

When there are 10 doors, win percentage when keeping original door is
10.6
On the other hand, if switching the win percentage is
89.3
