In [2]:
import numpy as np

In [8]:
array = np.array([1.0, 2.0, 3.0], dtype=np.float64)

In [10]:
array

array([1., 2., 3.])

In [11]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000)

# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

[0.5        0.125      0.33333333 0.5        0.16666667]
3.68 ms ± 75.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%timeit (1.0 / tableau_large)

5.73 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
x = np.random.rand(3,3)
x > 0.5

array([[ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [23]:
np.where(x > 0.5)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 2], dtype=int64))